export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const UNAUTHORISED_USER = 'UNAUTHORISED_USER';
export const REQUEST_LOGIN_USER = 'REQUEST_LOGIN_USER';
export const RECIEVE_LOGIN_USER_INFO = 'RECIEVE_LOGIN_USER_INFO';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
